package com.irr310.common.network.protocol;

public enum NetworkMessageType {
    HELLO, LOGIN_REQUEST, LOGIN_RESPONSE, SIGNUP_REQUEST, SIGNUP_RESPONSE, SHIP_LIST_REQUEST, SHIP_LIST, CAPACITY_UPDATE, PART_STATE_UPDATE_LIST, CAMERA_VIEW_OBJECT_LIST_REQUEST, WORLD_OBJECT_LIST, DAMAGE_NOTIFICATION, CELESTIAL_OBJECT_REMOVED_NOTIFICATION,
}
